"use client";
import { useEffect, useState } from "react";
import type { Project, ConversationMessage } from "@orc/shared";
import { getProjects } from "@/lib/projects";
import { getConversation, openConversation, postMessage } from "@/lib/conversations";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";
export function OrchestratorChat() { const [projects, setProjects] = useState<Project[]>([]); const [projectPath, setProjectPath] = useState(""); const [conversationId, setConversationId] = useState<string | null>(null); const [messages, setMessages] = useState<ConversationMessage[]>([]); const [content, setContent] = useState(""); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false); useEffect(() => { void getProjects().then((value) => { setProjects(value.projects); setProjectPath(value.projects[0]?.path ?? ""); }).catch((e: unknown) => setError(e instanceof Error ? e.message : "Unable to load projects")); }, []); async function select() { if (!projectPath) return; setBusy(true); try { const conversation = await openConversation(projectPath); const data = await getConversation(conversation.id); setConversationId(conversation.id); setMessages(data.messages); } catch (e) { setError(e instanceof Error ? e.message : "Unable to open conversation"); } finally { setBusy(false); } } async function submit(e: React.FormEvent) { e.preventDefault(); if (!conversationId || !content.trim()) return; setBusy(true); try { const result = await postMessage(conversationId, content); setMessages((current) => [...current, { id: crypto.randomUUID(), conversationId, role: "user", content, createdAt: new Date().toISOString() }, result.message]); setContent(""); } catch (e) { setError(e instanceof Error ? e.message : "Unable to send message"); } finally { setBusy(false); } } return <div className="flex max-w-3xl flex-col gap-5"><Card><CardHeader><CardTitle>Orchestrator</CardTitle></CardHeader><CardContent className="flex gap-2"><select value={projectPath} onChange={(e) => setProjectPath(e.target.value)} className="h-9 flex-1 rounded border bg-transparent px-2"><option value="">Select project</option>{projects.map((p) => <option key={p.id} value={p.path}>{p.name}</option>)}</select><Button onClick={() => void select()} disabled={busy || !projectPath}>Open chat</Button></CardContent></Card>{conversationId && <Card><CardContent className="flex min-h-80 flex-col gap-4 py-5">{messages.map((message) => <div key={message.id} className={message.role === "user" ? "self-end max-w-[80%] rounded bg-primary p-3 text-primary-foreground" : "max-w-[80%] rounded bg-muted p-3"}>{message.content}</div>)}<form onSubmit={submit} className="mt-auto flex gap-2"><Textarea value={content} onChange={(e) => setContent(e.target.value)} placeholder="Describe the engineering task or ask for status…" /><Button type="submit" disabled={busy}>{busy ? "Working…" : "Send"}</Button></form></CardContent></Card>}{error && <p className="text-sm text-status-error">{error}</p>}</div>; }
